### ISSUE TITLE
Perform DB update "per partes"

### ISSUE THREAD

**Issue by seepoww** [pali08/zanikle_obce_cz#2]
**Version:**
* master 1aac6cd35f846475a071169f75de4d156c3f055f

**Steps to reproduce:**
1. Click on Update DB
2. Confirm the update in dialog window by hitting "Yes"

**Current results:**
* It takes too long until DB is updated (I spent hours to update it and it won't just finish)

**Expected results:**
* DB is updated in chunks, per district, or it has failover mechanism when it fails so it does not need to be downloaded again completely

Possible solutions
* Perform the DB update per-partes or in chunks, if feasible
* Remember already downloaded indexes in case update crashes or it's restarted for other reason
* Download DB for particular district only, if possible

Notes:
* I am not sure if the original DB I downloaded with this repo already contained all necessary tables/content. I've just run into some issues when attempting to "draw" a map, and I though "oh this button might help me" :)

**Comment by pali08** [comment]
Fixed by keeping ID of last updated place (highest ID = latest place) and last page of database. However I have still kept option of full update of database. When user clicks on update database, they have two options:

a. Update newly added, which:
1. goes to remembered last page of database ordered by "Vloženo" (newest last)
2. checks all places on this page and each following page
3. If ID is bigger, than last remembered ID, get data and update database.

Database in this repository currently contains data until September 2022 (as of 2022-09-29) and pages are not updated much, so update takes few minutes at max.

The only issue is, that if some info for some place was changed after adding, this change will not be updated in database (date of last modification would be useful for this). That should not be a big problem, as it does not happen often and also there is just basic info in my program - user can click link to get more info like photo etc.

b. Do complete update. The problem here is, that it takes longer time (user is notified about it) and program gets grayed out. Gray out would happen for any function/command that does not happen immediately, but takes some time and program can not respond for events related to UI elements. This will be fixed in some follow up.
